objectName: Master_Framework__c
properties:
  rmNumber: RM_Number__c
  salesforceId: Id
  title: Long_Name__c
  terms: Framework_Terms__c
  pillar: Pillar__c
  category: CCS_Category__c
  status: Status__c
  startDate: Start_Date__c
  endDate: Effective_End_Date__c
  tendersOpenDate: OJEU_Date_Target__c
  tendersCloseDate: Tender_Closing_Date__c
  expectedLiveDate: Framework_Live_Date_Target__c
  expectedAwardDate: Award_Date_Target__c
  publishOnWebsite: Don_t_publish_as_Framework_on_website__c
  createDraftPage: Create_draft_web_page__c